version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=test_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  frontend:
    build:
      context: ./projnextauth
    ports:
      - "3001:3001"
    environment:
      NEXTAUTH_SECRET: teste9999999
      NEXTAUTH_URL: http://backend:3000
    depends_on:
      - backend

  playwright:
    build:
      context: ./playwright
    depends_on:
      - frontend

  cucumber:
    build:
      context: ./hellocucumber
    depends_on:
      - frontend

volumes:
  pgdata:
